spring:
  application:
    name: message-broker-receiver-other
  rabbitmq:
    username: myuser
    password: secret
    host: localhost
    port: 5672
    
logging:
  level:
    it:
      marco:
        messagebrokerreceiverother: DEBUG
